power <- read.csv(file="household_power_consumption.txt",sep=";", header=TRUE, colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings=c("?"))
somepower <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
png(filename="plot1.png", width=480,height=480)
hist(somepower$Global_active_power, main="Global Active Power",col="red",xlab="Global Active Power (kilowatts)")
dev.off()