power <- read.csv(file="household_power_consumption.txt",sep=";", header=TRUE, colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings=c("?"))
somepower <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
date_time <- strptime(paste(somepower$Date,somepower$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
png(filename="plot3.png", width=480,height=480)
plot(date_time,somepower$Sub_metering_1,type="l",ylab="Energy sub metering", xlab="")
lines(date_time,somepower$Sub_metering_2,col="red")
lines(date_time,somepower$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.off()